word_list = []
word_list.append(input("word ending in 'ing': "))
word_list.append(input("word ending in 'ing': "))
word_list.append(input("name an event : "))
word_list.append(input("Name a popular person: "))
word_list.append(input("name an adjective: "))
word_list.append(input("name a noun: "))
word_list.append(input("name a store: "))
word_list.append(input("think if a number: "))
word_list.append(input("name an adjective: "))
word_list.append(input("think of a plural noun: "))

print("The rain was %s and the people in the village were %s." % (print())
print("But in one household they were having a %s. They were dancing with %s." % ())
print("They were out causing a/an %s, but they soon ran out of %s and went to %s." % ())
print("When they came back the %s was still going on." % )
print("%s hours later someone had called the %s police." % ))
print("The police had shut down the %s, and" % )
print("everyone had gotten on/into their %s and went home." % )
