verb1 = input("verb ending in 'ing' ")
verb2 = input("verb ending in 'ing' ")
noun1 = input("event ")
prop_noun = input("popular person ")
adjective1 = input("Adjective ")
noun2 = input("noun ")
noun3 = input("name a store ")
digit = input("number ")
adjective2 = input("Adjective ")
noun4 = input("plural noun ")

print("The rain was %s and the people in the village were %s." % (verb1, verb2))
print("But in one household they were having a %s. They were dancing with %s." % (noun1, prop_noun))
print("They were out causing a/an %s, but they soon ran out of %s and went to %s." % (adjective1, noun2, noun3))
print("When they came back the %s was still going on." % noun1)
print("%s hours later someone had called the %s police." % (digit, adjective2))
print("The police had shut down the %s, and" % noun1)
print("everyone had gotten on/into their %s and went home." % noun4)
