word_list = []
word_list.append(input("word ending in 'ing': "))
word_list.append(input("word ending in 'ing': "))
word_list.append(input("name an event : "))
word_list.append(input("Name a popular person: "))
word_list.append(input("name an adjective: "))
word_list.append(input("name a noun: "))
word_list.append(input("name a store: "))
word_list.append(input("think if a number: "))
word_list.append(input("name an adjective: "))
word_list.append(input("think of a plural noun: "))

print("The rain was %s"  % word_list[0])
print("the people in the village were %s." % word_list[1])
print("But in one household they were having a %s."% word_list[2])
print(" They were dancing with %s." %  word_list[3])
print("They were out causing a/an %s"  % word_list[4])
print("but they soon ran out of %s" % word_list[5])
print("and went to %s." % word_list[6])
print("When they came back the %s was still going on." % word_list[7])
print("%s hours later someone had called the," % word_list[8])
print("%s police." % word_list[9])
print("The police had shut down the %s, and" % word_list[10])
print("everyone had gotten on/into their %s and went home." % word_list[11])
